### ISSUE TITLE
cant update shelly 1 to tasmota using script

### ISSUE THREAD

**Issue by jbreda007** [yaourdt/mgos-to-tasmota#103]
error is as follows:
python3 flash-shelly1.py -a
Installing zeroconf...
Updating pip...
DEPRECATION: distro-info 1.1build1 has a non-standard version number. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of distro-info or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Scanning for Shelly devices...
Traceback (most recent call last):
  File "/home/john/Desktop/TRANSFER/flash-shelly1.py", line 517, in <module>
    device_scan(args.hosts, args.do_all, args.dry_run, args.silent_run, args.target, args.exclude)
  File "/home/john/Desktop/TRANSFER/flash-shelly1.py", line 438, in device_scan
    zc.wait(100)
AttributeError: 'Zeroconf' object has no attribute 'wait'

**Comment by obueno** [comment]
https://github.com/yaourdt/mgos-to-tasmota/issues/51#issuecomment-1180719740
