### ISSUE TITLE
flash_shelly script does not run due to zeroconf error

### ISSUE THREAD

**Issue by OvisMaximus** [yaourdt/mgos-to-tasmota#107]
executed in the Power Shell on Windows 11

```
PS C:\Users\ada\bin\pythonScripts> python -V
Python 3.10.11
```

```
PS C:\Users\ada\bin\pythonScripts> python .\flash_shelly.py -a
Scanning for Shelly devices...
Traceback (most recent call last):
  File "C:\Users\lorenz\bin\pythonScripts\flash_shelly.py", line 517, in <module>
    device_scan(args.hosts, args.do_all, args.dry_run, args.silent_run, args.target, args.exclude)
  File "C:\Users\lorenz\bin\pythonScripts\flash_shelly.py", line 438, in device_scan
    zc.wait(100)
AttributeError: 'Zeroconf' object has no attribute 'wait'
```

**Comment by OvisMaximus** [comment]
It's a duplicate to #103
