### ISSUE TITLE
Flash script not working

### ISSUE THREAD

**Issue by jowgn** [yaourdt/mgos-to-tasmota#51]
Tried on a Mac running MacOS 11.4.
Error:
```
Scanning for Shelly devices...
Traceback (most recent call last):
  File "/Users/joschawagner/Downloads/mgos-to-tasmota-main/tools/flash-shelly.py", line 517, in <module>
    device_scan(args.hosts, args.do_all, args.dry_run, args.silent_run, args.target, args.exclude)
  File "/Users/joschawagner/Downloads/mgos-to-tasmota-main/tools/flash-shelly.py", line 438, in device_scan
    zc.wait(100)
AttributeError: 'Zeroconf' object has no attribute 'wait'
```

**Comment by dmayle** [comment]
You can change the `wait(100)` call to `async_wait(100)`
